### ISSUE TITLE
Getting NullPointerException on okhttp3

### ISSUE THREAD

**Issue by alokdesai-cuelogic** [Driftt/drift-sdk-android#10]
My application is live and I am getting this crash report on okhttp3.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean okhttp3.ad.a(java.lang.String)' on a null object reference
       at drift.com.drift.socket.Socket.chan(Unknown Source)
       at drift.com.drift.socket.Push.receive(Unknown Source)
       at drift.com.drift.socket.Channel.sendJoin(Unknown Source)
       at drift.com.drift.socket.Channel.rejoin(Unknown Source)
       at drift.com.drift.socket.Channel.rejoinUntilConnected(Unknown Source)
       at drift.com.drift.socket.Channel.join(Unknown Source)
       at drift.com.drift.socket.Channel$8.run(Unknown Source)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)

**Comment by eoinoconnell** [comment]
Hi, we haven't come across this on our side, is there anything in particular to reproduce the issue?

**Comment by alokdesai-cuelogic** [comment]
Hi, 
I am not able to reproduce this issue on my end. The application is live so I got this error on crashlytics report. Also I tested with long text messages and hyperlink messages but it is working fine on my end.

**Comment by imidhuntv** [comment]
Hi, 
I'm also experiencing the same issue in my app.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean okhttp3.WebSocket.send(java.lang.String)' on a null object reference
       at drift.com.drift.socket.Socket.push(SourceFile:286)
       at drift.com.drift.socket.Push.send(SourceFile:166)
       at drift.com.drift.socket.Channel.sendJoin(SourceFile:286)
       at drift.com.drift.socket.Channel.rejoin(SourceFile:219)
       at drift.com.drift.socket.Channel.rejoinUntilConnected(SourceFile:228)
       at drift.com.drift.socket.Channel.access$300(SourceFile:20)
       at drift.com.drift.socket.Channel$8.run(SourceFile:275)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)`
