### ISSUE TITLE
Fatal Exception: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by imidhuntv** [Driftt/drift-sdk-android#11]
This is a crash from our production app. 

`at okhttp3.internal.connection.RouteSelector.next(SourceFile:78)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:171)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at drift.com.drift.api.APIAuthTokenInterceptor.intercept(SourceFile:24)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
       at okhttp3.RealCall$AsyncCall.execute(SourceFile:135)
       at okhttp3.internal.NamedRunnable.run(SourceFile:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

I don't know how to repro this. But I have got 8 of the same from 7 different users. Happening in all kind of devices with OS 6,7 and 8.

**Comment by eoinoconnell** [comment]
Hey, thanks for the trace, we're continuing to look into it but are having trouble reproducing it on our end also, we will update here as soon as we have more information but we are continuing to look into this
